spring:
  application:
    name: UserService

  datasource:
    url: jdbc:mysql://localhost:3307/users_db
    username: useradmin
    password: userpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs