spring:
  application:
    name: UserService

  datasource:
    url: ${USER_DB_URL:jdbc:mysql://localhost:3307/users_db}
    username: ${USER_DB_USERNAME:useradmin}
    password: ${USER_DB_PASSWORD:userpass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  kafka:
    bootstrap-servers: ${USER_KAFKA_SERVERS:localhost:9092}
    producer:
      client-id: UserService-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000 # 15 min in milliseconds
