spring:
  application:
    name: ProductCatalogService
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:h2:mem:productsdb}
    driver-class-name: ${PRODUCT_DB_DRIVER:org.h2.Driver}
    username: ${PRODUCT_DB_USERNAME:sa}
    password: ${PRODUCT_DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
